name: poker_rules_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19

# Run commands to generate splash screen
# flutter clean
# flutter pub get
# flutter pub get flutter_native_splash:create

# general command:
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: '#111111'
  image: assets/ace_cards.png
  

flutter:
  uses-material-design: true
  assets:
    - assets/
